### PR TITLE
Updated base path for Symbl Summary

### PR DESCRIPTION
**Pull request by janhavi-ai**
[Symbl's summarisation](https://docs.symbl.ai/docs/conversation-api/summary/) has been Alpha released and is now available from the base path "api.symbl.ai".

### CODE REVIEW

**Comment by mjabali** [comment]
@javiermolsanz would you be able to look at this when you have a chance? The Labs API has been deprecated and this PR takes care of it. Also, the demo app deployed is failing to generate the Summary because of this issue.

**Comment by javiermolsanz** [comment]
Thanks Marcelo. I merged it

I would need to deploy the app with the new path. Will try to do so this
week.

**Comment by mjabali** [comment]
Hi @javiermolsanz, is there any chance you could redeploy this in the next few days? I’d like to use this to demo some of our capabilities during the Enterprise Connect event. Thanks.

**Comment by javiermolsanz** [comment]
Hi Marcelo,

Just redeployed it now. Great to know that you'd like to show this during
Enterprise Connect. Let me know how it goes or if you need further
assistance.

**Pull request merged**
